spring:
  application:
    name: ReserVault
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
  frontend:
    url: "http://localhost:5173"
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB_NAME}
      socket-timeout: 30000
      connect-timeout: 10000
      server-selection-timeout: 15000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
  config:
    import: "optional:file:.env[.properties]"
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}