spring:
  application:
    name: ReserVault
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 7200000
  frontend:
    url: "http://localhost:5173"
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB_NAME}
      socket-timeout: 30000
      connect-timeout: 10000
      server-selection-timeout: 15000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
  config:
    import: "optional:file:.env[.properties]"
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

reservault: # development seeders, cleanups
  seeders:
    enabled: true # MasterSeederConfig (controls all seeders) (disable after first start if cleanup disabled)
    roles: true # RoleSeederConfig (REQUIRED for any start)
    admin: true # AdminSeederConfig (REQUIRED for admin account creation)
    manager: false # ManagerSeederConfig (optional example data)
    hotels: false # HotelSeederConfig (optional example data)
    offers: false # OfferSeederConfig (optional example data)
  cleanup:
    enabled: false # CloudinaryCleanupConfig, DatabaseCleanupConfig (optional cleanup)